version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"             # ✅ CRA default
    volumes:
      - ./frontend:/app         # Source code
      - /app/node_modules       # Keep node_modules inside the container
    stdin_open: true            # ✅ Needed for CRA dev server
    tty: true
    depends_on:
      - backend